#!/bin/sh
#
# Create swap file $SWAP_F.
# User can choose between 1GB, 2GB, 3GB and 4GB.
# Activate it and add it to /etc/fstab

SWAP_F=/var/swap

Help()
{
	echo "create_swapfile: creates $SWAP_F swap file."
	echo "Syntax: create_swapfile n"
	echo "options:"
	echo "n     swap file size (in GB). Choose between 1, 2, 3 and 4."
	echo
}

while getopts ":h" option; do
	case $option in
		h)
			Help
			exit;;
		\?)
			echo "Error: Invalid option"
			exit;;
	esac
done

if ! [[ "$1" =~ ^[1-4]+$ ]]
    then
        echo "Error: only integers between 1 and 4."
	Help
	exit 1
fi

SWAP_SIZE=$(( $1 * 1048576))

# Create $SWAP_F if it doesn't already exist
if test -f "$SWAP_F"; then
	echo "$SWAP_F already exists!"
else
	echo "Creating /var/swap with dd."
	echo "This might take a while, be patient."
	dd if=/dev/urandom of=$SWAP_F bs=1024 count="$SWAP_SIZE" status=none >/dev/null 2>&1
	chmod 600 $SWAP_F
fi

# Enable $SWAP_F if it's not already enabled
if [[ $(swapon -s | grep "$SWAP_F") ]]; then
	echo "$SWAP_F is already enabled as swap."
else
	echo "Enabling $SWAP_F as swap file."
	mkswap $SWAP_F >/dev/null 2>&1
	swapon $SWAP_F >/dev/null 2>&1
fi

# Add $SWAP_F to fstab if it doesn't already exist
if [[ $(cat /etc/fstab | grep "$SWAP_F") ]]; then
	echo "$SWAP_F entry already exists in /etc/fstab."
else
	echo "Adding $SWAP_F entry to /etc/fstab so it's persistent to reboot."
	echo "$SWAP_F   none    swap    sw    0   0" >> /etc/fstab
fi

