#!/usr/bin/env python3

# This file is part of IOTA honeycombOS Linux Distribution
# (https://github.com/iotaledger/meta-iota)
# Copyright (c) 2020 IOTA Stiftung

import os
import shutil
import sys
import errno

status = os.system('systemctl is-active --quiet goshimmer') # will return 0 for active else inactive.
if not status:
    try:
        print("Stopping goshimmer.service.")
        os.system("systemctl stop goshimmer")
    except:
        print("Error while stopping goshimmer systemd service.")


mainnetdb_path = "/var/lib/goshimmer/mainnetdb"
exists = os.path.isdir(mainnetdb_path)

if not exists:
    print("GoShimmer mainnetdb is already clean. Nothing to do.")
else:
    try:
        shutil.rmtree(mainnetdb_path)
        print("GoShimmer mainnetdb has been cleaned. You can restart the service now.")
    except IOError as e:
        errorn, strerror = e.args
        if errorn == errno.EACCES:
            print("You need root permissions to do this!")
            sys.exit(1)

